name: Deploy On Production
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Executing remote command
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        KEY: ${{ secrets.SSHKEY }}
        debug: ${{ secrets.DEBUG }}
        script: pwd
        